/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

/* top =  1  */
/* src = "../rtl/fir_chip.sv:1.8" */
module fir_chip(clk, rst, in, out);
  wire [6:0] \$21y ;
  wire [8:0] \$22y ;
  wire [9:0] \$23y ;
  /* src = "../rtl/fir_chip.sv:8.7" */
  wire chip_clk;
  /* src = "../rtl/fir_chip.sv:11.13" */
  wire [3:0] chip_in;
  wire [10:0] chip_out;
  /* src = "../rtl/fir_chip.sv:9.7" */
  wire chip_rst;
  /* src = "../rtl/fir_chip.sv:3.17" */
  input clk;
  wire clk;
  /* src = "../rtl/adder.sv:3.24" */
  wire [31:0] \i_fir.a1.in1 ;
  wire [5:0] \i_fir.a1.in2 ;
  wire [7:0] \i_fir.a1.in3 ;
  wire [5:0] \i_fir.a1.in4 ;
  /* src = "../rtl/adder.sv:3.44" */
  wire [31:0] \i_fir.a1.in5 ;
  /* src = "../rtl/adder.sv:4.25" */
  wire [31:0] \i_fir.a1.out ;
  /* src = "../rtl/fir.sv:4.17" */
  wire \i_fir.clk ;
  /* src = "../rtl/dq.sv:4.18" */
  wire \i_fir.i1.clk ;
  /* src = "../rtl/dq.sv:3.33" */
  wire [3:0] \i_fir.i1.d ;
  /* src = "../rtl/dq.sv:5.24" */
  wire [3:0] \i_fir.i1.q ;
  /* src = "../rtl/dq.sv:4.23" */
  wire \i_fir.i1.rst ;
  /* src = "../rtl/dq.sv:4.18" */
  wire \i_fir.i2.clk ;
  /* src = "../rtl/dq.sv:3.33" */
  wire [3:0] \i_fir.i2.d ;
  /* src = "../rtl/dq.sv:5.24" */
  wire [3:0] \i_fir.i2.q ;
  /* src = "../rtl/dq.sv:4.23" */
  wire \i_fir.i2.rst ;
  /* src = "../rtl/dq.sv:4.18" */
  wire \i_fir.i3.clk ;
  /* src = "../rtl/dq.sv:3.33" */
  wire [3:0] \i_fir.i3.d ;
  /* src = "../rtl/dq.sv:5.24" */
  wire [3:0] \i_fir.i3.q ;
  /* src = "../rtl/dq.sv:4.23" */
  wire \i_fir.i3.rst ;
  /* src = "../rtl/dq.sv:4.18" */
  wire \i_fir.i4.clk ;
  /* src = "../rtl/dq.sv:3.33" */
  wire [3:0] \i_fir.i4.d ;
  /* src = "../rtl/dq.sv:5.24" */
  wire [3:0] \i_fir.i4.q ;
  /* src = "../rtl/dq.sv:4.23" */
  wire \i_fir.i4.rst ;
  /* src = "../rtl/dq.sv:4.18" */
  wire \i_fir.i5.clk ;
  /* src = "../rtl/dq.sv:3.33" */
  wire [3:0] \i_fir.i5.d ;
  /* src = "../rtl/dq.sv:5.24" */
  wire [3:0] \i_fir.i5.q ;
  /* src = "../rtl/dq.sv:4.23" */
  wire \i_fir.i5.rst ;
  /* src = "../rtl/fir.sv:3.32" */
  wire [3:0] \i_fir.in ;
  /* src = "../rtl/multiplier.sv:4.24" */
  wire [3:0] \i_fir.m1.i ;
  /* src = "../rtl/multiplier.sv:5.25" */
  wire [31:0] \i_fir.m1.o ;
  /* src = "../rtl/multiplier.sv:4.24" */
  wire [3:0] \i_fir.m2.i ;
  wire [5:0] \i_fir.m2.o ;
  /* src = "../rtl/multiplier.sv:4.24" */
  wire [3:0] \i_fir.m3.i ;
  wire [7:0] \i_fir.m3.o ;
  /* src = "../rtl/multiplier.sv:4.24" */
  wire [3:0] \i_fir.m4.i ;
  wire [5:0] \i_fir.m4.o ;
  /* src = "../rtl/multiplier.sv:4.24" */
  wire [3:0] \i_fir.m5.i ;
  /* src = "../rtl/multiplier.sv:5.25" */
  wire [31:0] \i_fir.m5.o ;
  /* src = "../rtl/fir.sv:9.19" */
  wire [31:0] \i_fir.o1 ;
  wire [5:0] \i_fir.o2 ;
  wire [7:0] \i_fir.o3 ;
  wire [5:0] \i_fir.o4 ;
  /* src = "../rtl/fir.sv:9.35" */
  wire [31:0] \i_fir.o5 ;
  /* src = "../rtl/fir.sv:5.25" */
  wire [31:0] \i_fir.out ;
  /* src = "../rtl/fir.sv:8.19" */
  wire [3:0] \i_fir.q1 ;
  /* src = "../rtl/fir.sv:8.23" */
  wire [3:0] \i_fir.q2 ;
  /* src = "../rtl/fir.sv:8.27" */
  wire [3:0] \i_fir.q3 ;
  /* src = "../rtl/fir.sv:8.31" */
  wire [3:0] \i_fir.q4 ;
  /* src = "../rtl/fir.sv:8.35" */
  wire [3:0] \i_fir.q5 ;
  /* src = "../rtl/fir.sv:4.22" */
  wire \i_fir.rst ;
  /* src = "../rtl/fir_chip.sv:4.32" */
  input [3:0] in;
  wire [3:0] in;
  /* src = "../rtl/fir_chip.sv:5.25" */
  output [31:0] out;
  wire [31:0] out;
  /* src = "../rtl/fir_chip.sv:3.22" */
  input rst;
  wire rst;
  /* src = "../rtl/adder.sv:8.11-8.20" */
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd5)
  ) \$21  (
    .A(\i_fir.i1.q [3:2]),
    .B(\i_fir.i2.q ),
    .Y(\$21y [6:2])
  );
  /* src = "../rtl/adder.sv:8.11-8.26" */
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd5)
  ) \$22  (
    .A(\$21y [6:4]),
    .B(\i_fir.i3.q ),
    .Y(\$22y [8:4])
  );
  /* src = "../rtl/adder.sv:8.11-8.32" */
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd7),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd8)
  ) \$23  (
    .A({ \$22y [8:4], \$21y [3:2] }),
    .B(\i_fir.i4.q ),
    .Y(\$23y [9:2])
  );
  /* src = "../rtl/adder.sv:8.11-8.38" */
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd10),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd11)
  ) \$24  (
    .A({ \$23y [9:2], \i_fir.i1.q [1:0] }),
    .B(\i_fir.i5.q ),
    .Y(chip_out)
  );
  /* src = "../rtl/dq.sv:8.1" */
  \$adff  #(
    .ARST_POLARITY(32'd1),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) \$driver$i_fir.i1.q  (
    .ARST(chip_rst),
    .CLK(chip_clk),
    .D(chip_in),
    .Q(\i_fir.i1.q )
  );
  /* src = "../rtl/dq.sv:8.1" */
  \$adff  #(
    .ARST_POLARITY(32'd1),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) \$driver$i_fir.i2.q  (
    .ARST(chip_rst),
    .CLK(chip_clk),
    .D(\i_fir.i1.q ),
    .Q(\i_fir.i2.q )
  );
  /* src = "../rtl/dq.sv:8.1" */
  \$adff  #(
    .ARST_POLARITY(32'd1),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) \$driver$i_fir.i3.q  (
    .ARST(chip_rst),
    .CLK(chip_clk),
    .D(\i_fir.i2.q ),
    .Q(\i_fir.i3.q )
  );
  /* src = "../rtl/dq.sv:8.1" */
  \$adff  #(
    .ARST_POLARITY(32'd1),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) \$driver$i_fir.i4.q  (
    .ARST(chip_rst),
    .CLK(chip_clk),
    .D(\i_fir.i3.q ),
    .Q(\i_fir.i4.q )
  );
  /* src = "../rtl/dq.sv:8.1" */
  \$adff  #(
    .ARST_POLARITY(32'd1),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) \$driver$i_fir.i5.q  (
    .ARST(chip_rst),
    .CLK(chip_clk),
    .D(\i_fir.i4.q ),
    .Q(\i_fir.i5.q )
  );
  /* src = "../rtl/fir_chip.sv:16.16" */
  sg13g2_IOPadIn pad_clk (
    .p2c(chip_clk),
    .pad(clk)
  );
  /* src = "../rtl/fir_chip.sv:19.16" */
  sg13g2_IOPadIn pad_in0 (
    .p2c(chip_in[0]),
    .pad(in[0])
  );
  /* src = "../rtl/fir_chip.sv:20.16" */
  sg13g2_IOPadIn pad_in1 (
    .p2c(chip_in[1]),
    .pad(in[1])
  );
  /* src = "../rtl/fir_chip.sv:21.16" */
  sg13g2_IOPadIn pad_in2 (
    .p2c(chip_in[2]),
    .pad(in[2])
  );
  /* src = "../rtl/fir_chip.sv:22.16" */
  sg13g2_IOPadIn pad_in3 (
    .p2c(chip_in[3]),
    .pad(in[3])
  );
  /* src = "../rtl/fir_chip.sv:24.21" */
  sg13g2_IOPadOut16mA pad_out0 (
    .c2p(chip_out[0]),
    .pad(out[0])
  );
  /* src = "../rtl/fir_chip.sv:25.21" */
  sg13g2_IOPadOut16mA pad_out1 (
    .c2p(chip_out[1]),
    .pad(out[1])
  );
  /* src = "../rtl/fir_chip.sv:34.21" */
  sg13g2_IOPadOut16mA pad_out10 (
    .c2p(chip_out[10]),
    .pad(out[10])
  );
  /* src = "../rtl/fir_chip.sv:35.21" */
  sg13g2_IOPadOut16mA pad_out11 (
    .c2p(1'h0),
    .pad(out[11])
  );
  /* src = "../rtl/fir_chip.sv:36.21" */
  sg13g2_IOPadOut16mA pad_out12 (
    .c2p(1'h0),
    .pad(out[12])
  );
  /* src = "../rtl/fir_chip.sv:37.21" */
  sg13g2_IOPadOut16mA pad_out13 (
    .c2p(1'h0),
    .pad(out[13])
  );
  /* src = "../rtl/fir_chip.sv:38.21" */
  sg13g2_IOPadOut16mA pad_out14 (
    .c2p(1'h0),
    .pad(out[14])
  );
  /* src = "../rtl/fir_chip.sv:39.21" */
  sg13g2_IOPadOut16mA pad_out15 (
    .c2p(1'h0),
    .pad(out[15])
  );
  /* src = "../rtl/fir_chip.sv:40.21" */
  sg13g2_IOPadOut16mA pad_out16 (
    .c2p(1'h0),
    .pad(out[16])
  );
  /* src = "../rtl/fir_chip.sv:41.21" */
  sg13g2_IOPadOut16mA pad_out17 (
    .c2p(1'h0),
    .pad(out[17])
  );
  /* src = "../rtl/fir_chip.sv:42.21" */
  sg13g2_IOPadOut16mA pad_out18 (
    .c2p(1'h0),
    .pad(out[18])
  );
  /* src = "../rtl/fir_chip.sv:43.21" */
  sg13g2_IOPadOut16mA pad_out19 (
    .c2p(1'h0),
    .pad(out[19])
  );
  /* src = "../rtl/fir_chip.sv:26.21" */
  sg13g2_IOPadOut16mA pad_out2 (
    .c2p(chip_out[2]),
    .pad(out[2])
  );
  /* src = "../rtl/fir_chip.sv:44.21" */
  sg13g2_IOPadOut16mA pad_out20 (
    .c2p(1'h0),
    .pad(out[20])
  );
  /* src = "../rtl/fir_chip.sv:45.21" */
  sg13g2_IOPadOut16mA pad_out21 (
    .c2p(1'h0),
    .pad(out[21])
  );
  /* src = "../rtl/fir_chip.sv:46.21" */
  sg13g2_IOPadOut16mA pad_out22 (
    .c2p(1'h0),
    .pad(out[22])
  );
  /* src = "../rtl/fir_chip.sv:47.21" */
  sg13g2_IOPadOut16mA pad_out23 (
    .c2p(1'h0),
    .pad(out[23])
  );
  /* src = "../rtl/fir_chip.sv:48.21" */
  sg13g2_IOPadOut16mA pad_out24 (
    .c2p(1'h0),
    .pad(out[24])
  );
  /* src = "../rtl/fir_chip.sv:49.21" */
  sg13g2_IOPadOut16mA pad_out25 (
    .c2p(1'h0),
    .pad(out[25])
  );
  /* src = "../rtl/fir_chip.sv:50.21" */
  sg13g2_IOPadOut16mA pad_out26 (
    .c2p(1'h0),
    .pad(out[26])
  );
  /* src = "../rtl/fir_chip.sv:51.21" */
  sg13g2_IOPadOut16mA pad_out27 (
    .c2p(1'h0),
    .pad(out[27])
  );
  /* src = "../rtl/fir_chip.sv:52.21" */
  sg13g2_IOPadOut16mA pad_out28 (
    .c2p(1'h0),
    .pad(out[28])
  );
  /* src = "../rtl/fir_chip.sv:53.21" */
  sg13g2_IOPadOut16mA pad_out29 (
    .c2p(1'h0),
    .pad(out[29])
  );
  /* src = "../rtl/fir_chip.sv:27.21" */
  sg13g2_IOPadOut16mA pad_out3 (
    .c2p(chip_out[3]),
    .pad(out[3])
  );
  /* src = "../rtl/fir_chip.sv:54.21" */
  sg13g2_IOPadOut16mA pad_out30 (
    .c2p(1'h0),
    .pad(out[30])
  );
  /* src = "../rtl/fir_chip.sv:55.21" */
  sg13g2_IOPadOut16mA pad_out31 (
    .c2p(1'h0),
    .pad(out[31])
  );
  /* src = "../rtl/fir_chip.sv:28.21" */
  sg13g2_IOPadOut16mA pad_out4 (
    .c2p(chip_out[4]),
    .pad(out[4])
  );
  /* src = "../rtl/fir_chip.sv:29.21" */
  sg13g2_IOPadOut16mA pad_out5 (
    .c2p(chip_out[5]),
    .pad(out[5])
  );
  /* src = "../rtl/fir_chip.sv:30.21" */
  sg13g2_IOPadOut16mA pad_out6 (
    .c2p(chip_out[6]),
    .pad(out[6])
  );
  /* src = "../rtl/fir_chip.sv:31.21" */
  sg13g2_IOPadOut16mA pad_out7 (
    .c2p(chip_out[7]),
    .pad(out[7])
  );
  /* src = "../rtl/fir_chip.sv:32.21" */
  sg13g2_IOPadOut16mA pad_out8 (
    .c2p(chip_out[8]),
    .pad(out[8])
  );
  /* src = "../rtl/fir_chip.sv:33.21" */
  sg13g2_IOPadOut16mA pad_out9 (
    .c2p(chip_out[9]),
    .pad(out[9])
  );
  /* src = "../rtl/fir_chip.sv:17.16" */
  sg13g2_IOPadIn pad_rst (
    .p2c(chip_rst),
    .pad(rst)
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:57.36" */
  sg13g2_IOPadVdd pad_vdd0 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:58.36" */
  sg13g2_IOPadVdd pad_vdd1 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:63.38" */
  sg13g2_IOPadIOVdd pad_vddio0 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:64.38" */
  sg13g2_IOPadIOVdd pad_vddio1 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:60.36" */
  sg13g2_IOPadVss pad_vss0 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:61.36" */
  sg13g2_IOPadVss pad_vss1 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:66.38" */
  sg13g2_IOPadIOVss pad_vssio0 (
  );
  /* keep = "true" */
  /* src = "../rtl/fir_chip.sv:67.38" */
  sg13g2_IOPadIOVss pad_vssio1 (
  );
  assign \$21y [1:0] = \i_fir.i1.q [1:0];
  assign \$22y [3:0] = { \$21y [3:2], \i_fir.i1.q [1:0] };
  assign \$23y [1:0] = \i_fir.i1.q [1:0];
  assign \i_fir.a1.in1  = { 28'h0000000, \i_fir.i1.q  };
  assign \i_fir.a1.in2  = { \i_fir.i2.q , 2'h0 };
  assign \i_fir.a1.in3  = { \i_fir.i3.q , 4'h0 };
  assign \i_fir.a1.in4  = { \i_fir.i4.q , 2'h0 };
  assign \i_fir.a1.in5  = { 28'h0000000, \i_fir.i5.q  };
  assign \i_fir.a1.out  = { 21'h000000, chip_out };
  assign \i_fir.clk  = chip_clk;
  assign \i_fir.i1.clk  = chip_clk;
  assign \i_fir.i1.d  = chip_in;
  assign \i_fir.i1.rst  = chip_rst;
  assign \i_fir.i2.clk  = chip_clk;
  assign \i_fir.i2.d  = \i_fir.i1.q ;
  assign \i_fir.i2.rst  = chip_rst;
  assign \i_fir.i3.clk  = chip_clk;
  assign \i_fir.i3.d  = \i_fir.i2.q ;
  assign \i_fir.i3.rst  = chip_rst;
  assign \i_fir.i4.clk  = chip_clk;
  assign \i_fir.i4.d  = \i_fir.i3.q ;
  assign \i_fir.i4.rst  = chip_rst;
  assign \i_fir.i5.clk  = chip_clk;
  assign \i_fir.i5.d  = \i_fir.i4.q ;
  assign \i_fir.i5.rst  = chip_rst;
  assign \i_fir.in  = chip_in;
  assign \i_fir.m1.i  = \i_fir.i1.q ;
  assign \i_fir.m1.o  = { 28'h0000000, \i_fir.i1.q  };
  assign \i_fir.m2.i  = \i_fir.i2.q ;
  assign \i_fir.m2.o  = { \i_fir.i2.q , 2'h0 };
  assign \i_fir.m3.i  = \i_fir.i3.q ;
  assign \i_fir.m3.o  = { \i_fir.i3.q , 4'h0 };
  assign \i_fir.m4.i  = \i_fir.i4.q ;
  assign \i_fir.m4.o  = { \i_fir.i4.q , 2'h0 };
  assign \i_fir.m5.i  = \i_fir.i5.q ;
  assign \i_fir.m5.o  = { 28'h0000000, \i_fir.i5.q  };
  assign \i_fir.o1  = { 28'h0000000, \i_fir.i1.q  };
  assign \i_fir.o2  = { \i_fir.i2.q , 2'h0 };
  assign \i_fir.o3  = { \i_fir.i3.q , 4'h0 };
  assign \i_fir.o4  = { \i_fir.i4.q , 2'h0 };
  assign \i_fir.o5  = { 28'h0000000, \i_fir.i5.q  };
  assign \i_fir.out  = { 21'h000000, chip_out };
  assign \i_fir.q1  = \i_fir.i1.q ;
  assign \i_fir.q2  = \i_fir.i2.q ;
  assign \i_fir.q3  = \i_fir.i3.q ;
  assign \i_fir.q4  = \i_fir.i4.q ;
  assign \i_fir.q5  = \i_fir.i5.q ;
  assign \i_fir.rst  = chip_rst;
endmodule
